version: '3'
services:  
  vuejs:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      command: npm run dev
      env_file:
        - frontend/.env
      environment:
        - NODE_ENV=development